version: '3.8'

services:
  merk:
    build: .
    env_file: .env.local
    environment:
      SURREALDB_URL: ws://surrealdb:8000
    ports:
      - "9678:9678"
    depends_on:
      surrealdb:
        condition: service_healthy

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: start --log trace --username ${SURREALDB_USER:-usairim} --password ${SURREALDB_PASS:-musanif} memory
    healthcheck:
      test: [ "CMD", "/surreal", "isready", "--endpoint", "http://localhost:8000" ]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
